export const globalConfig = {
    baseurl:"http://192.168.233.23:5000",
    baseimgurl:"http://192.168.233.23:5000",
    mapConfig: {
        "Init": {
            "projection": "EPSG:3857",
            "center": [
                4.166741,
                23.661341
            ],
            "zoom": 16
        },
        "BaseUrl": "http://120.38.253.6:6080/arcgis/rest/services/",
        "Extent": {
            "XMin": 4.153052,
            "YMin": 23.647721,
            "XMax": 4.181006,
            "YMax": 23.674876,
            "SpatialReference": 3857
        },
        "CustomLayer": [{
            "type": "TILE",
            "url": "http://1.117.34.229:8081/tiles",
            "layer": "tiles",
            "isBaseLayer": "true",
            "layerID": "4",
            "layerCnName": "影像",
            "layerEnName": "tiles",
            "img": "./static/images/layerid4.png",
            "alwayShow": "true",
            "layerIndex": "4",
            "defaultVisible": true
        },
            {
                "type": "WMS",
                "url": "http://1.117.34.229:8080/geoserver/pscj/wms",
                "layer": "pscj:wsline",
                "projection": "EPSG:3857",
                "isBaseLayer": "false",
                "tiled": true,
                "layerID": "6",
                "layerCnName": "管线",
                "layerEnName": "wsline",
                "serverType": "geoserver",
                "alwayShow": "false",
                "layerIndex": "6",
                "defaultVisible": true,
                "onlyselect": false
            },
            {
                "type": "WMS",
                "url": "http://1.117.34.229:8080/geoserver/pscj/wms",
                "layer": "pscj:wspoint",
                "projection": "EPSG:3857",
                "isBaseLayer": "false",
                "tiled": true,
                "layerID": "7",
                "layerCnName": "管点",
                "layerEnName": "wspoint",
                "serverType": "geoserver",
                "alwayShow": "false",
                "layerIndex": "7",
                "defaultVisible": true,
                "onlyselect": false
            }
        ],
        "Token": "3f590eecb9241236ca44c5d76bbf5179",
        "PointAttributes": {
            "JS": "供水管点",
            "OBJECTID": "要素ID",
            "P_TYPE": "管线类型",
            "PTYPE": "管线类型",
            "SCODE": "设施类别",
            "EXP_NO": "物探点号",
            "PNO": "设施编号",
            "FEATURE": "特征",
            "SUBSID": "附属物",
            "ADDRESS": "地址",
            "MATERIAL": "材质",
            "SPEC": "规格",
            "DEEP": "埋深",
            "H": "高程",
            "X": "X坐标",
            "Y": "Y坐标",
            "ROTANG": "旋转角度",
            "MAPNUMBER": "图幅号",
            "MDATE": "建设年代",
            "ROAD": "所在道路",
            "ONOFF": "开关状态",
            "STAURS": "目前状况",
            "SETUP": "是否安装",
            "DETAIL": "详图",
            "KIND": "闸门种类",
            "WDEEP": "井深",
            "KEYTYPE": "钥匙型号",
            "ROADTYPE": "路面类别",
            "MAKER": "生产厂家",
            "SUR_DATE": "入库日期",
            "DB_DATE": "更新日期",
            "P_ID": "工程号",
            "REMARK": "备注",
            "SHAPE": "要素类别"
        },
        "LineAttributes": {
            "JS": "供水管线",
            "OBJECTID": "要素ID",
            "P_TYPE": "管线类型",
            "PTYPE": "管线类型",
            "SPOINT": "起点号",
            "S_POINT": "起点号",
            "EPOINT": "终点号",
            "E_POINT": "终点号",
            "ADDRESS": "地址",
            "MATERIAL": "材质",
            "D_S": "管径",
            "S_DEEP": "起点埋深",
            "E_DEEP": "终点埋深",
            "S_H": "起点高程",
            "E_H": "终点高程",
            "MDATE": "建设年代",
            "RNAME": "所在道路",
            "FLOW_D": "流向",
            "FLOWDIRECT": "流向",
            "LLENGTH": "长度",
            "CDATE": "验收日期",
            "DETAIL": "详图",
            "SUR_DATE": "探测时间",
            "DB_DATE": "入库时间",
            "UP_DATE": "入库时间",
            "P_ID": "工程号",
            "REMARK": "备注",
            "SHAPE": "要素类别",
            "SHAPE_Length": "管线长度"
        }
    },
    api: {
        "addPoint": "/addPoint",
        "delPoint": "/delPoint",
        "modifyPoint": "/modifyPoint",
        "movePoint": "/movePoint",
        "addLine": "/addLine",
        "delLine": "/delLine",
        "modifyLine": "/modifyLine"
    },
}
